version: '3.5'

services:
  app:
    image: containerized-nextjs
    build:
      context: .
      dockerfile: Dockerfile
    container_name: containerized-next-js
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
